version: '3.4'

services:

  movie-db:
    image: mysql:8.0.26
    container_name: movie-db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_DATABASE: 'movie_trash'
      MYSQL_USER: 'movie_user'
      MYSQL_PASSWORD: 'movie_pass'
    ports:
      - '3306:3306'
    volumes:
      - movie-db:/var/lib/mysql

  movie-service:
    build:
      context: .\
      dockerfile: Dockerfile
    image: 'movie-service:latest'
    container_name: movie-service
    restart: unless-stopped
    ports:
      - '8080:8080'
    environment:
      - 'SPRING_PROFILES_ACTIVE=docker'
    depends_on:
      - movie-db

  movie-sender:
    build:
      context: .\
      dockerfile: Dockerfile-sender
    image: 'movie-sender:latest'
    container_name: movie-sender
    restart: unless-stopped
    ports:
      - '9090:9090'
    environment:
      - 'SPRING_PROFILES_ACTIVE=docker_sender'

  movie-frontend:
    build:
      context: .\
      dockerfile: Dockerfile-frontend
    image: 'movie-frontend:latest'
    container_name: movie-frontend
    restart: unless-stopped
    ports:
      - '8585:8585'

  movie-rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'movie-rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq/data/:/var/lib/movie-rabbitmq
      - ./rabbitmq/log/:/var/log/movie-rabbitmq

volumes:
  movie-db: { }
  movie-rabbitmq: { }

